services:
  db:
    image: mongo:6-focal
    restart: unless-stopped
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
  
  db-ui:
    image: mongo-express
    restart: unless-stopped
    depends_on: 
      - db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@db:27017/

    ports:
      - 9090:8081
